export Qudits

"""
    Qudit(dim)

a site type to represent qudit sites, that is `dim` level systems carrying the
generalized Pauli operators rather than spin operators. It is parametrised by the dimension
of the Hilbert space.

Writing ``d`` for that dimension and ``\\omega = e^{2i\\pi/d}`` for the corresponding
``d``-th root of unity, the clock operator acts as
``Z_d|n\\rangle = \\omega^n |n\\rangle`` and the shift operator as
``X_d|n\\rangle = |n+1 \\mod d\\rangle``. Both are unitary of order ``d`` and obey the
Weyl relation ``Z_d X_d = \\omega X_d Z_d``.

`Qudit(2)` is the qubit, with `Zd` and `Xd` equal to the Pauli `Z` and `X`, and `Hd` and
`S` equal to the Hadamard and phase gates. `Zd` and `Xd` are named differently because for
``d > 2`` they are no longer involutions.

`Hd`, `S` and `Sumd` generate the Clifford group, that is the unitaries mapping the
operators generated by `Zd` and `Xd` onto themselves by conjugation.

# Examples

    Qudit(3)

# States

`"0", "1", ...`

# Operators

- `N`  : the level operator, `diag(0, 1, ..., d-1)`
- `Zd` : the clock operator
- `Xd` : the shift operator
- `Hd` : the Fourier operator, also known as the generalized Hadamard gate
- `S`  : the phase operator, of order ``d`` for odd ``d`` and ``2d`` for even ``d``
- `Sumd(d)` : the two qudit generalized controlled not, see `Sumd`
"""
struct Qudit <: AbstractSite
    dim::Int
end

dim(a::Qudit) = a.dim

@def_operators(Qudit(2),
[
    selfadjoint_op =>
    [
        N = s -> [ i == j ? i - 1. : 0. for i in 1:dim(s), j in 1:dim(s) ],
    ],
    plain_op =>
    [
        Zd = s -> [ i == j ? exp(2im * π * (i - 1) / dim(s)) : 0.0im
                    for i in 1:dim(s), j in 1:dim(s) ],
        Xd = s -> [ mod(i - j, dim(s)) == 1 ? 1.0 + 0im : 0.0im
                    for i in 1:dim(s), j in 1:dim(s) ],
        Hd = s -> [ exp(2im * π * (i - 1) * (j - 1) / dim(s)) / √dim(s)
                    for i in 1:dim(s), j in 1:dim(s) ],
        S = s -> begin
            d = dim(s)
            τ = exp(1im * π * (d^2 + 1) / d)      # a square root of ω
            [ i == j ? τ^((i - 1)^2) : 0.0im for i in 1:d, j in 1:d ]
        end,
    ]
])

"""
    Sumd(d)

the generalized controlled not of two qudits of dimension `d`, acting as
``|i, j\\rangle \\mapsto |i, i + j \\mod d\\rangle``. `Sumd(2)` is the usual CNOT.

It is built as ``\\sum_i P_i \\otimes X_d^i``, that is as an operator expression rather
than as a matrix, so that it can be used in a hamiltonian as well as applied as a gate.

# Examples

    Sumd(3)(1, 2)
"""
Sumd(d::Int) =
    Operator{2}("Sumd($d)", sum(Proj(i) ⊗ Xd^i for i in 0:d-1), plain_op)

@create_site_module(Qudits, [Qudit, N, Zd, Xd, Hd, S, Sumd])
