name: CI
on:
  push:
    branches:
      - main
      - dev
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          # the minimum [compat] promises, the current stable, the upcoming release
          - {os: ubuntu-latest, arch: x64, version: '1.10'}
          - {os: ubuntu-latest, arch: x64, version: '1'}
          - {os: ubuntu-latest, arch: x64, version: 'pre'}
          # Apple Silicon: reachable since MKL stopped being a hard dependency
          - {os: macos-latest, arch: aarch64, version: '1'}
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      # the tests already run instrumented: `coverage` defaults to true in julia-runtest,
      # so collecting the result costs nothing more than gathering the .cov files
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: true
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
